### ISSUE TITLE
Calling `calculate_crc()` with data="A" and length=1 returns 0.

### ISSUE THREAD

**Issue by larsonma** [ce4951/networking#13]
@piparocj When I call `calculate_crc()`, passing it a sting "A", and a length 1, 0 is returned when 0x62 should be returned (per our earlier discussion).

https://github.com/ce4951/networking/blob/2f0d2814e8be37001622962f2a44c401f1b91462/src/crc.c#L58

**Comment by piparocj** [comment]
Are you just passing in "A" or are you passing the header along with it?

**Comment by larsonma** [comment]
You're right, I wasn't passing in the right amount of data.


On Oct 28, 2018, at 5:51 PM, piparocj <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you just passing in "A" or are you passing the header along with it?

**Comment by larsonma** [comment]
So, per Dr. Rothe's comments in class, we should only be applying the CRC on the message field. I think this open issue would then be a valid concern for our system.

**Comment by piparocj** [comment]
I really thought it was the whole data from the examples in lecture and in the book. Either way, I think this will be a super easy fix and it is much easier to test.

**Comment by larsonma** [comment]
It seems like you would want the CRC to be done for the entire frame. Either way, if we can get it to work with just a single byte of data, then we should be fine either way.

**Comment by piparocj** [comment]
Do we calculate CRC from MSB to LSB? So, if we get the message "AB", do we get the CRC of byte "B" and then byte "A", or byte "A" and then byte "B"? aka: should we get CRC=0x87 or CRC=0xB1?

**Comment by larsonma** [comment]
I believe A then B

**Comment by piparocj** [comment]
Okay, well if it ends up being opposite, it's an easy fix.

**Comment by larsonma** [comment]
The frame is received MSB to LSB, so that's why I believe it should be "A" then "B".

**Comment by piparocj** [comment]
I was thinking like, if you did `char *str = "AB"` then "A" would be the least significant byte.

**Comment by larsonma** [comment]
I think that if I passed you a string containing "AB" and you performed the CRC from left to right, that would be the correct way to do it. (I.e. A then B)

**Comment by piparocj** [comment]
Fixed with #14. Closing.
